/*!40000 ALTER TABLE `category` DISABLE KEYS */;
LOCK TABLES `category` WRITE;
INSERT INTO `category` VALUES  (1,'Cashmere',6,'cashmere'),
 (2,'Silk',6,'silk'),
 (3,'Woolen',6,'woolen'),
 (4,'Caps',7,'caps'),
 (5,'Beenie',7,'beenie'),
 (6,'Scarves',0,'scarves'),
 (7,'Hats',0,'hats'),
 (8,'red-eye',5,'red-eye');
UNLOCK TABLES;
/*!40000 ALTER TABLE `category` ENABLE KEYS */;

/*!40000 ALTER TABLE `product` DISABLE KEYS */;
LOCK TABLES `product` WRITE;
INSERT INTO `product` VALUES  (1,7,'product-1','product 1','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut arcu. Vivamus vel massa id orci faucibus euismod. Morbi condimentum magna. Proin ac augue quis ante placerat venenatis. Ut nulla diam, lacinia vitae, ornare et, laoreet a, tellus. Morbi dolor orci, adipiscing non, rhoncus id, pretium non, orci. Nullam non mi sit amet tellus placerat feugiat. Aenean adipiscing auctor risus. Morbi vitae tellus. Etiam sed erat. Integer eget lectus eu lorem varius porta. Donec at ipsum et neque euismod ultrices. Aenean elementum elit eget justo. Etiam quis nisl. In hac habitasse platea dictumst. ','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi justo diam, dictum ac, ultricies nec.','10.99',0,'Yes'),
 (2,7,'product-2','product 2','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut arcu. Vivamus vel massa id orci faucibus euismod. Morbi condimentum magna. Proin ac augue quis ante placerat venenatis. Ut nulla diam, lacinia vitae, ornare et, laoreet a, tellus. Morbi dolor orci, adipiscing non, rhoncus id, pretium non, orci. Nullam non mi sit amet tellus placerat feugiat. Aenean adipiscing auctor risus. Morbi vitae tellus. Etiam sed erat. Integer eget lectus eu lorem varius porta. Donec at ipsum et neque euismod ultrices. Aenean elementum elit eget justo. Etiam quis nisl. In hac habitasse platea dictumst. ','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi justo diam, dictum ac, ultricies nec.','11.99',0,'Yes'),
 (3,6,'product-3','product 3','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut arcu. Vivamus vel massa id orci faucibus euismod. Morbi condimentum magna. Proin ac augue quis ante placerat venenatis. Ut nulla diam, lacinia vitae, ornare et, laoreet a, tellus. Morbi dolor orci, adipiscing non, rhoncus id, pretium non, orci. Nullam non mi sit amet tellus placerat feugiat. Aenean adipiscing auctor risus. Morbi vitae tellus. Etiam sed erat. Integer eget lectus eu lorem varius porta. Donec at ipsum et neque euismod ultrices. Aenean elementum elit eget justo. Etiam quis nisl. In hac habitasse platea dictumst. ','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi justo diam, dictum ac, ultricies nec.','11.99',0,'Yes');
INSERT INTO `product` VALUES  (4,5,'product-4','product 4','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut arcu. Vivamus vel massa id orci faucibus euismod. Morbi condimentum magna. Proin ac augue quis ante placerat venenatis. Ut nulla diam, lacinia vitae, ornare et, laoreet a, tellus. Morbi dolor orci, adipiscing non, rhoncus id, pretium non, orci. Nullam non mi sit amet tellus placerat feugiat. Aenean adipiscing auctor risus. Morbi vitae tellus. Etiam sed erat. Integer eget lectus eu lorem varius porta. Donec at ipsum et neque euismod ultrices. Aenean elementum elit eget justo. Etiam quis nisl. In hac habitasse platea dictumst. ','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi justo diam, dictum ac, ultricies nec.','11.99',0,'Yes'),
 (5,4,'product-5','product 5','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut arcu. Vivamus vel massa id orci faucibus euismod. Morbi condimentum magna. Proin ac augue quis ante placerat venenatis. Ut nulla diam, lacinia vitae, ornare et, laoreet a, tellus. Morbi dolor orci, adipiscing non, rhoncus id, pretium non, orci. Nullam non mi sit amet tellus placerat feugiat. Aenean adipiscing auctor risus. Morbi vitae tellus. Etiam sed erat. Integer eget lectus eu lorem varius porta. Donec at ipsum et neque euismod ultrices. Aenean elementum elit eget justo. Etiam quis nisl. In hac habitasse platea dictumst. ','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi justo diam, dictum ac, ultricies nec.','11.99',0,'Yes'),
 (6,3,'product-6','product 6','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut arcu. Vivamus vel massa id orci faucibus euismod. Morbi condimentum magna. Proin ac augue quis ante placerat venenatis. Ut nulla diam, lacinia vitae, ornare et, laoreet a, tellus. Morbi dolor orci, adipiscing non, rhoncus id, pretium non, orci. Nullam non mi sit amet tellus placerat feugiat. Aenean adipiscing auctor risus. Morbi vitae tellus. Etiam sed erat. Integer eget lectus eu lorem varius porta. Donec at ipsum et neque euismod ultrices. Aenean elementum elit eget justo. Etiam quis nisl. In hac habitasse platea dictumst. ','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi justo diam, dictum ac, ultricies nec.','11.99',0,'Yes');
INSERT INTO `product` VALUES  (7,2,'product-7','product 7','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut arcu. Vivamus vel massa id orci faucibus euismod. Morbi condimentum magna. Proin ac augue quis ante placerat venenatis. Ut nulla diam, lacinia vitae, ornare et, laoreet a, tellus. Morbi dolor orci, adipiscing non, rhoncus id, pretium non, orci. Nullam non mi sit amet tellus placerat feugiat. Aenean adipiscing auctor risus. Morbi vitae tellus. Etiam sed erat. Integer eget lectus eu lorem varius porta. Donec at ipsum et neque euismod ultrices. Aenean elementum elit eget justo. Etiam quis nisl. In hac habitasse platea dictumst. ','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi justo diam, dictum ac, ultricies nec.','11.99',50,'Yes'),
 (8,1,'product-8','product 8','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut arcu. Vivamus vel massa id orci faucibus euismod. Morbi condimentum magna. Proin ac augue quis ante placerat venenatis. Ut nulla diam, lacinia vitae, ornare et, laoreet a, tellus. Morbi dolor orci, adipiscing non, rhoncus id, pretium non, orci. Nullam non mi sit amet tellus placerat feugiat. Aenean adipiscing auctor risus. Morbi vitae tellus. Etiam sed erat. Integer eget lectus eu lorem varius porta. Donec at ipsum et neque euismod ultrices. Aenean elementum elit eget justo. Etiam quis nisl. In hac habitasse platea dictumst. ','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi justo diam, dictum ac, ultricies nec.','11.99',0,'Yes'),
 (9,1,'product-9','product 9','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut arcu. Vivamus vel massa id orci faucibus euismod. Morbi condimentum magna. Proin ac augue quis ante placerat venenatis. Ut nulla diam, lacinia vitae, ornare et, laoreet a, tellus. Morbi dolor orci, adipiscing non, rhoncus id, pretium non, orci. Nullam non mi sit amet tellus placerat feugiat. Aenean adipiscing auctor risus. Morbi vitae tellus. Etiam sed erat. Integer eget lectus eu lorem varius porta. Donec at ipsum et neque euismod ultrices. Aenean elementum elit eget justo. Etiam quis nisl. In hac habitasse platea dictumst. ','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi justo diam, dictum ac, ultricies nec.','11.99',0,'Yes');
INSERT INTO `product` VALUES  (10,2,'product-10','product 10','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut arcu. Vivamus vel massa id orci faucibus euismod. Morbi condimentum magna. Proin ac augue quis ante placerat venenatis. Ut nulla diam, lacinia vitae, ornare et, laoreet a, tellus. Morbi dolor orci, adipiscing non, rhoncus id, pretium non, orci. Nullam non mi sit amet tellus placerat feugiat. Aenean adipiscing auctor risus. Morbi vitae tellus. Etiam sed erat. Integer eget lectus eu lorem varius porta. Donec at ipsum et neque euismod ultrices. Aenean elementum elit eget justo. Etiam quis nisl. In hac habitasse platea dictumst. ','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi justo diam, dictum ac, ultricies nec.','11.99',0,'Yes'),
 (11,3,'product-11','product 11','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut arcu. Vivamus vel massa id orci faucibus euismod. Morbi condimentum magna. Proin ac augue quis ante placerat venenatis. Ut nulla diam, lacinia vitae, ornare et, laoreet a, tellus. Morbi dolor orci, adipiscing non, rhoncus id, pretium non, orci. Nullam non mi sit amet tellus placerat feugiat. Aenean adipiscing auctor risus. Morbi vitae tellus. Etiam sed erat. Integer eget lectus eu lorem varius porta. Donec at ipsum et neque euismod ultrices. Aenean elementum elit eget justo. Etiam quis nisl. In hac habitasse platea dictumst. ','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi justo diam, dictum ac, ultricies nec.','11.99',0,'Yes'),
 (12,4,'product-12','product 12','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut arcu. Vivamus vel massa id orci faucibus euismod. Morbi condimentum magna. Proin ac augue quis ante placerat venenatis. Ut nulla diam, lacinia vitae, ornare et, laoreet a, tellus. Morbi dolor orci, adipiscing non, rhoncus id, pretium non, orci. Nullam non mi sit amet tellus placerat feugiat. Aenean adipiscing auctor risus. Morbi vitae tellus. Etiam sed erat. Integer eget lectus eu lorem varius porta. Donec at ipsum et neque euismod ultrices. Aenean elementum elit eget justo. Etiam quis nisl. In hac habitasse platea dictumst. ','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi justo diam, dictum ac, ultricies nec.','11.99',0,'Yes');
INSERT INTO `product` VALUES  (13,5,'product-13','product 13','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut arcu. Vivamus vel massa id orci faucibus euismod. Morbi condimentum magna. Proin ac augue quis ante placerat venenatis. Ut nulla diam, lacinia vitae, ornare et, laoreet a, tellus. Morbi dolor orci, adipiscing non, rhoncus id, pretium non, orci. Nullam non mi sit amet tellus placerat feugiat. Aenean adipiscing auctor risus. Morbi vitae tellus. Etiam sed erat. Integer eget lectus eu lorem varius porta. Donec at ipsum et neque euismod ultrices. Aenean elementum elit eget justo. Etiam quis nisl. In hac habitasse platea dictumst. ','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi justo diam, dictum ac, ultricies nec.','11.99',0,'Yes'),
 (14,6,'product-14','product 14','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut arcu. Vivamus vel massa id orci faucibus euismod. Morbi condimentum magna. Proin ac augue quis ante placerat venenatis. Ut nulla diam, lacinia vitae, ornare et, laoreet a, tellus. Morbi dolor orci, adipiscing non, rhoncus id, pretium non, orci. Nullam non mi sit amet tellus placerat feugiat. Aenean adipiscing auctor risus. Morbi vitae tellus. Etiam sed erat. Integer eget lectus eu lorem varius porta. Donec at ipsum et neque euismod ultrices. Aenean elementum elit eget justo. Etiam quis nisl. In hac habitasse platea dictumst. ','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi justo diam, dictum ac, ultricies nec.','11.99',0,'Yes'),
 (15,7,'product-15','product 15','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut arcu. Vivamus vel massa id orci faucibus euismod. Morbi condimentum magna. Proin ac augue quis ante placerat venenatis. Ut nulla diam, lacinia vitae, ornare et, laoreet a, tellus. Morbi dolor orci, adipiscing non, rhoncus id, pretium non, orci. Nullam non mi sit amet tellus placerat feugiat. Aenean adipiscing auctor risus. Morbi vitae tellus. Etiam sed erat. Integer eget lectus eu lorem varius porta. Donec at ipsum et neque euismod ultrices. Aenean elementum elit eget justo. Etiam quis nisl. In hac habitasse platea dictumst. ','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi justo diam, dictum ac, ultricies nec.','11.99',0,'Yes');
INSERT INTO `product` VALUES  (16,6,'product-16','product 16','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut arcu. Vivamus vel massa id orci faucibus euismod. Morbi condimentum magna. Proin ac augue quis ante placerat venenatis. Ut nulla diam, lacinia vitae, ornare et, laoreet a, tellus. Morbi dolor orci, adipiscing non, rhoncus id, pretium non, orci. Nullam non mi sit amet tellus placerat feugiat. Aenean adipiscing auctor risus. Morbi vitae tellus. Etiam sed erat. Integer eget lectus eu lorem varius porta. Donec at ipsum et neque euismod ultrices. Aenean elementum elit eget justo. Etiam quis nisl. In hac habitasse platea dictumst. ','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi justo diam, dictum ac, ultricies nec.','11.99',0,'Yes'),
 (17,5,'product-17','product 17','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut arcu. Vivamus vel massa id orci faucibus euismod. Morbi condimentum magna. Proin ac augue quis ante placerat venenatis. Ut nulla diam, lacinia vitae, ornare et, laoreet a, tellus. Morbi dolor orci, adipiscing non, rhoncus id, pretium non, orci. Nullam non mi sit amet tellus placerat feugiat. Aenean adipiscing auctor risus. Morbi vitae tellus. Etiam sed erat. Integer eget lectus eu lorem varius porta. Donec at ipsum et neque euismod ultrices. Aenean elementum elit eget justo. Etiam quis nisl. In hac habitasse platea dictumst. ','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi justo diam, dictum ac, ultricies nec.','11.99',0,'Yes'),
 (18,4,'product-18','product 18','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut arcu. Vivamus vel massa id orci faucibus euismod. Morbi condimentum magna. Proin ac augue quis ante placerat venenatis. Ut nulla diam, lacinia vitae, ornare et, laoreet a, tellus. Morbi dolor orci, adipiscing non, rhoncus id, pretium non, orci. Nullam non mi sit amet tellus placerat feugiat. Aenean adipiscing auctor risus. Morbi vitae tellus. Etiam sed erat. Integer eget lectus eu lorem varius porta. Donec at ipsum et neque euismod ultrices. Aenean elementum elit eget justo. Etiam quis nisl. In hac habitasse platea dictumst. ','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi justo diam, dictum ac, ultricies nec.','11.99',0,'Yes');
INSERT INTO `product` VALUES  (19,8,'product-19','product 19','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut arcu. Vivamus vel massa id orci faucibus euismod. Morbi condimentum magna. Proin ac augue quis ante placerat venenatis. Ut nulla diam, lacinia vitae, ornare et, laoreet a, tellus. Morbi dolor orci, adipiscing non, rhoncus id, pretium non, orci. Nullam non mi sit amet tellus placerat feugiat. Aenean adipiscing auctor risus. Morbi vitae tellus. Etiam sed erat. Integer eget lectus eu lorem varius porta. Donec at ipsum et neque euismod ultrices. Aenean elementum elit eget justo. Etiam quis nisl. In hac habitasse platea dictumst. ','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi justo diam, dictum ac, ultricies nec.','11.99',0,'Yes');
UNLOCK TABLES;
/*!40000 ALTER TABLE `product` ENABLE KEYS */;

/*!40000 ALTER TABLE `productImage` DISABLE KEYS */;
LOCK TABLES `productImage` WRITE;
INSERT INTO `productImage` VALUES  (1,5,'sm_raver.png','raver.jpg','Yes'),
 (2,19,'sm_raver.png','raver.jpg','Yes'),
 (3,18,'sm_wooly_beenie.png','wooly_beenie.jpg','Yes'),
 (4,17,'sm_raver.png','raver.jpg','Yes'),
 (5,16,'sm_sc.png','sc.png','Yes'),
 (6,15,'sm_raver.png','raver.jpg','Yes'),
 (7,14,'sm_sc.png','sc.png','Yes'),
 (8,13,'sm_wooly_beenie.png','wooly_beenie.jpg','Yes'),
 (9,12,'sm_wooly_beenie.png','wooly_beenie.jpg','Yes'),
 (10,11,'sm_sc.png','sc.png','Yes'),
 (11,10,'sm_sc.png','sc.png','Yes'),
 (12,9,'sm_sc.png','sc.png','Yes'),
 (13,8,'sm_sc.png','sc.png','Yes'),
 (14,7,'sm_sc.png','sc.png','Yes'),
 (15,6,'sm_sc.png','sc.png','Yes'),
 (16,5,'sm_raver.png','raver.jpg','No'),
 (17,4,'sm_wooly_beenie.png','wooly_beenie.jpg','Yes'),
 (18,3,'sm_sc.png','sc.png','Yes'),
 (19,2,'sm_raver.png','raver.jpg','Yes'),
 (20,1,'sm_raver.png','raver.jpg','Yes'),
 (21,1,'sm_raver.png','raver.jpg','No');
UNLOCK TABLES;
/*!40000 ALTER TABLE `productImage` ENABLE KEYS */;

/*!40000 ALTER TABLE `user` DISABLE KEYS */;
LOCK TABLES `user` WRITE;
INSERT INTO `user` VALUES  (1,'Mr','Keith','Pope','me@me.com','28f92fdb9ac4133ce2267079c0ce324c5c09d463','da660cb994e214937a83afe5d215e401','Admin');
UNLOCK TABLES;
/*!40000 ALTER TABLE `user` ENABLE KEYS */;