<h2 class="noDisplay">Main Navigation</h2>
<div class="main-nav">
    <ul class="clearfix">
        <li class="current">
            <a href="" title="Homepage">Store</a>
        </li>
        <li>
            <a href="" title="logout">Logout</a>
        </li>
        <li>
            <a href="" title="login">Login</a>
        </li>
        <li>
            <a href="" title="register">Register</a>
        </li>
        <li>
            <a href="" title="about">About</a>
        </li>
        <li>
            <a href="" title="Contact">Contact</a>
        </li>
        <li>
            <a href="" title="administration area">Admin</a>
        </li>
    </ul>
</div>