<h2 class="noDisplay">Main Navigation</h2>
<div class="main-nav">
    <ul class="clearfix">
        <li><a href="<?=$this->url(array('controller' => 'customer', 'action' => 'list')); ?>" title="Customers">Customers</a></li>
        <li><a href="<?=$this->url(array('controller' => 'catalog', 'action' => 'list')); ?>" title="Catalog">Catalog</a></li>
        <li><a href="/" title="Homepage">Store</a></li>
    </ul>
</div>
