<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Fatal Error - Please contact support</title>
</head>
<body>
    <h1>Fatal Error</h1>
    <p>
        The system was unable to start the application, this may be a temporary error, please try again later.
    </p>
    <p>
        A log of this error has been sent to the support team.
    </p>
</body>
</html>
